-- MySQL Script generated by MySQL Workbench
-- 04/22/16 19:37:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SatkeEvidencniSystem
-- -----------------------------------------------------
-- Databaze pro evidenci zakazniku, faktur a aut prodanych spolecnosti SATKE
-- 
DROP SCHEMA IF EXISTS `SatkeEvidencniSystem` ;

-- -----------------------------------------------------
-- Schema SatkeEvidencniSystem
--
-- Databaze pro evidenci zakazniku, faktur a aut prodanych spolecnosti SATKE
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SatkeEvidencniSystem` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `SatkeEvidencniSystem` ;

-- -----------------------------------------------------
-- Table `SatkeEvidencniSystem`.`klient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SatkeEvidencniSystem`.`klient` ;

CREATE TABLE IF NOT EXISTS `SatkeEvidencniSystem`.`klient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(45) NOT NULL,
  `email` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SatkeEvidencniSystem`.`auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SatkeEvidencniSystem`.`auto` ;

CREATE TABLE IF NOT EXISTS `SatkeEvidencniSystem`.`auto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `spz` VARCHAR(45) NOT NULL,
  `vin` VARCHAR(45) NOT NULL,
  `stk` VARCHAR(45) NOT NULL,
  `rokVyroby` YEAR NOT NULL,
  `znacka` VARCHAR(45) NOT NULL DEFAULT 'Opel',
  `model` VARCHAR(45) NULL,
  `olej` DATE NULL COMMENT 'Datum posledni vymeny oleje\n',
  `poznamka` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `vin_UNIQUE` (`vin` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SatkeEvidencniSystem`.`autoVlastni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SatkeEvidencniSystem`.`autoVlastni` ;

CREATE TABLE IF NOT EXISTS `SatkeEvidencniSystem`.`autoVlastni` (
  `id` INT NOT NULL,
  `klient_id` INT NOT NULL,
  `auto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_autoVlastni_klient_idx` (`klient_id` ASC),
  INDEX `fk_autoVlastni_auto1_idx` (`auto_id` ASC),
  CONSTRAINT `fk_autoVlastni_klient`
    FOREIGN KEY (`klient_id`)
    REFERENCES `SatkeEvidencniSystem`.`klient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_autoVlastni_auto1`
    FOREIGN KEY (`auto_id`)
    REFERENCES `SatkeEvidencniSystem`.`auto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SatkeEvidencniSystem`.`faktura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SatkeEvidencniSystem`.`faktura` ;

CREATE TABLE IF NOT EXISTS `SatkeEvidencniSystem`.`faktura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datumVydani` TIMESTAMP NOT NULL DEFAULT TIMESTAMP(),
  `path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SatkeEvidencniSystem`.`komu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SatkeEvidencniSystem`.`komu` ;

CREATE TABLE IF NOT EXISTS `SatkeEvidencniSystem`.`komu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `faktura_id` INT NOT NULL,
  `klient_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_komu_faktura1_idx` (`faktura_id` ASC),
  INDEX `fk_komu_klient1_idx` (`klient_id` ASC),
  CONSTRAINT `fk_komu_faktura1`
    FOREIGN KEY (`faktura_id`)
    REFERENCES `SatkeEvidencniSystem`.`faktura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_komu_klient1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `SatkeEvidencniSystem`.`klient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SatkeEvidencniSystem`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SatkeEvidencniSystem`.`address` ;

CREATE TABLE IF NOT EXISTS `SatkeEvidencniSystem`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SatkeEvidencniSystem`.`klient_has_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SatkeEvidencniSystem`.`klient_has_address` ;

CREATE TABLE IF NOT EXISTS `SatkeEvidencniSystem`.`klient_has_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_klient_has_address_address1_idx` (`address_id` ASC),
  INDEX `fk_klient_has_address_klient1_idx` (`klient_id` ASC),
  CONSTRAINT `fk_klient_has_address_klient1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `SatkeEvidencniSystem`.`klient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_klient_has_address_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `SatkeEvidencniSystem`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SatkeEvidencniSystem`.`motor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SatkeEvidencniSystem`.`motor` ;

CREATE TABLE IF NOT EXISTS `SatkeEvidencniSystem`.`motor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `objem` FLOAT(2,2) NOT NULL,
  `kod` VARCHAR(45) NOT NULL COMMENT 'unikatni kod motoru\n',
  `vykon` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `kod_UNIQUE` (`kod` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SatkeEvidencniSystem`.`auto_has_motor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SatkeEvidencniSystem`.`auto_has_motor` ;

CREATE TABLE IF NOT EXISTS `SatkeEvidencniSystem`.`auto_has_motor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auto_id` INT NOT NULL,
  `motor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auto_has_motor_motor1_idx` (`motor_id` ASC),
  INDEX `fk_auto_has_motor_auto1_idx` (`auto_id` ASC),
  CONSTRAINT `fk_auto_has_motor_auto1`
    FOREIGN KEY (`auto_id`)
    REFERENCES `SatkeEvidencniSystem`.`auto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_auto_has_motor_motor1`
    FOREIGN KEY (`motor_id`)
    REFERENCES `SatkeEvidencniSystem`.`motor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SatkeEvidencniSystem`.`klient_has_auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SatkeEvidencniSystem`.`klient_has_auto` ;

CREATE TABLE IF NOT EXISTS `SatkeEvidencniSystem`.`klient_has_auto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `auto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_klient_has_auto_auto1_idx` (`auto_id` ASC),
  INDEX `fk_klient_has_auto_klient1_idx` (`klient_id` ASC),
  CONSTRAINT `fk_klient_has_auto_klient1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `SatkeEvidencniSystem`.`klient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_klient_has_auto_auto1`
    FOREIGN KEY (`auto_id`)
    REFERENCES `SatkeEvidencniSystem`.`auto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SatkeEvidencniSystem`.`auto_has_faktura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SatkeEvidencniSystem`.`auto_has_faktura` ;

CREATE TABLE IF NOT EXISTS `SatkeEvidencniSystem`.`auto_has_faktura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auto_id` INT NOT NULL,
  `faktura_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auto_has_faktura_auto1_idx` (`auto_id` ASC),
  CONSTRAINT `fk_auto_has_faktura_auto1`
    FOREIGN KEY (`auto_id`)
    REFERENCES `SatkeEvidencniSystem`.`auto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SatkeEvidencniSystem`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SatkeEvidencniSystem`.`admin` ;

CREATE TABLE IF NOT EXISTS `SatkeEvidencniSystem`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
